apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-helper
  namespace: default
spec:
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-helper-sa
          containers:
          - name: ecr-helper
            image: nginx #will be replced 
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: ecr-helper-secrets 
              - configMapRef:
                  name: ecr-helper-cm
            command:
              - /bin/bash
              - -c
              - |-
                ECR_TOKEN="$(aws ecr get-login-password --region us-east-1)"
                kubectl delete secret --ignore-not-found $DOCKER_SECRET_NAME
                kubectl create secret docker-registry $DOCKER_SECRET_NAME --docker-server=https://${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com --docker-username=AWS --docker-password=${ECR_TOKEN}
                echo "Secret was successfully updated at $(date)"
          restartPolicy: Never