name: workflow
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' 

      - name: Compile code with Maven
        run: mvn compile 

  test:
    name: test
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: test code with Maven
        run: mvn test
  
  security-scan:
    name: security-scan
    runs-on: ubuntu-24.04
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.33.1
        continue-on-error: true
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
          

  code-quality:
    name: code-quality
    runs-on: ubuntu-24.04
    needs: security-scan
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # Caches Maven dependencies for faster subsequent builds
          cache: 'maven'
      
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Thumama610_end-to-end-devsecops-cicd-pipeline

  build-and-upload-artifact:
    name: build-and-upload-artifact
    runs-on: ubuntu-24.04
    needs: code-quality
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # Caches Maven dependencies for faster subsequent builds
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml # Command to build the project and create the artifact

      - name: test jar file
        run: |
          ls
          ls target/

      - uses: actions/upload-artifact@v4
        with:
          name: maven-app
          path: target/database_service_project-0.0.5-SNAPSHOT.jar
          retention-days: 30 

  docker-build-scan-push:
    name: docker-build-scan-push
    runs-on: ubuntu-24.04
    needs: build-and-upload-artifact
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: thumama610/maven-app:${{ github.sha }}
          push: false

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: thumama610/maven-app:${{ github.sha }}
          format: table
      #    exit-code: 1
      #    severity: CRITICAL,HIGH
       
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_USER_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Login to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      # Build Docker image
      - name: Build Image
        run: |
          docker build -t thumama610/maven-app .

      # Tag Image
      - name: Tag Image
        run: |
          docker tag thumama610/maven-app:${{ github.sha }} ${{ secrets.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/thumama610/maven-app:${{ github.sha }}

      # Push Image
      - name: Push Image
        run: |
          docker push ${{ secrets.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/thumama610/maven-app:${{ github.sha }}

  modify-manifest-and-copy-to-the-server:
    name: modify-manifest-and-copy-to-the-server
    runs-on: ubuntu-24.04
    needs: docker-build-scan-push
    steps:
      - name: checkout 
        uses: actions/checkout@v4

      - name: update deployment file
        run: |
          sed -i "s|image: .*|image: thumama610/maven-app:${{ github.sha }}|g" deployment-service.yaml

      - name: inject k8s files into the server
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > my-key.pem
          sudo chmod 400 my-key.pem
          scp -o StrictHostKeyChecking=no -i my-key.pem deployment-service.yaml ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_IP_ADDRESS }}:~

  ssh-and-apply-to-k8s:
    name: ssh-and-apply-changes
    runs-on: ubuntu-24.04
    needs: modify-manifest-and-copy-to-the-server
    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_IP_ADDRESS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            kubectl apply -f deployment-service.yaml